version: '3.9'
services:
  blaze:
    image: samply/blaze:latest
    restart: unless-stopped
    environment:
      BASE_URL: http://localhost:8080
    ports:
      - ${BLAZE_PORT:-8080}:8080
    volumes:
      - blaze-data:/app/data
  fhir-facade:
    build: ./facade_app
    restart: unless-stopped
    environment:
      FHIR_SERVER_URL: ${FHIR_SERVER_URL:-http://blaze:8080/fhir/}
      FACADE_PORT: ${FACADE_PORT:-8082}
      PAGE_SIZE: ${PAGE_SIZE:-50}
      PAGE_STORE_TIME: ${PAGE_STORE_TIME:-1200}
      PAGING_STORE: ${PAGING_STORE:-LOCAL}
      MONGO_DB_URL: ${MONGO_DB_URL:-mongodb://host.docker.internal:27017}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      BA_USER_NAME: ${BA_USER_NAME}
      BA_PASSWORD: ${BA_PASSWORD}
      PROVISION_CONFIG: ${PROVISION_CONFIG}
      RESOURCE_CONFIG: ${RESOURCE_CONFIG}
      SSL_CERT: ${SSL_CERT}
      SSL_KEY: ${SSL_KEY}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-1}
      PROCESSES_PER_WORKER: ${PROCESSES_PER_WORKER:-1}
      MP_CHUNK_SIZE: ${MP_CHUNK_SIZE:-50}
      INTERNAL_PAGE_SIZE: ${INTERNAL_PAGE_SIZE:-2000}
      CONSENT_CACHE_TIME: ${CONSENT_CACHE_TIME:-60}
    env_file:
      - .env
    ports: 
      - ${FACADE_PORT:-8082}:8082
    
volumes:
    blaze-data:
