#Add all resources that are supposed to be limited by consent status
#This must include a 'Date' Attribute with a relative Path from the Resource to a necessary Date field including its name
#As well as a similar 'Subject' field with the relative Path to a necessary Patient Identifier
#Paths are represented as follows: path/to/the/subject/field
Resources:
  Observation:
    Date: "issued"
    Subject: "subject/reference"
  Encounter:
    Date: "period/start"
    Subject: "subject/reference"
  Procedure:
    Date: "performedPeriod/"
    Subject: "subject/reference"
  Specimen:
    Date: "collection/collectedDateTime"
    Subject: "subject/reference"
